# Generated by Django 6.0 on 2026-06-18 14:29

from django.db import migrations, models


def fill_order_codes(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.filter(code__isnull=True).order_by('id'):
        prefix = 'S' if order.order_type == 'saboy' else 'O'
        Order.objects.filter(pk=order.pk).update(code=f'{prefix}-{order.pk:05d}')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(fill_order_codes, migrations.RunPython.noop),
    ]
