# Generated by Django 6.0 on 2026-06-19 21:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_payment_items(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    PaymentItem = apps.get_model('payments', 'PaymentItem')
    OrderItem = apps.get_model('orders', 'OrderItem')

    snapshots = []
    for payment in Payment.objects.iterator():
        order_items = OrderItem.objects.filter(order_id=payment.order_id).select_related('product')
        for item in order_items:
            snapshots.append(PaymentItem(
                payment_id=payment.pk,
                product_id=item.product_id,
                product_name=item.product.name,
                quantity=item.quantity,
                unit_price=item.unit_price,
                total_price=item.quantity * item.unit_price,
            ))
    PaymentItem.objects.bulk_create(snapshots)


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_amount'),
        ('products', '0002_product_banner_image_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=140)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.payment')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='products.product')),
            ],
            options={
                'verbose_name': 'To‘lov mahsuloti',
                'verbose_name_plural': 'To‘lov mahsulotlari',
                'ordering': ('id',),
            },
        ),
        migrations.RunPython(backfill_payment_items, migrations.RunPython.noop),
    ]
