# Generated by Django 6.0 on 2026-06-21 14:25

import decimal
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_payment_methods(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    PaymentPart = apps.get_model('payments', 'PaymentPart')
    PaymentPart.objects.bulk_create([
        PaymentPart(
            payment_id=payment.pk,
            method='terminal' if payment.method == 'card' else payment.method,
            amount=payment.amount,
        )
        for payment in Payment.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentitem_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('click', 'Click'), ('terminal', 'Terminal')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))])),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='payments.payment')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('payment', 'method'), name='unique_payment_method')],
            },
        ),
        migrations.RunPython(migrate_payment_methods, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
    ]
