# Generated by Django 6.0 on 2026-06-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stol kategoriyasi',
                'verbose_name_plural': 'Stol kategoriyalari',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Bo‘sh'), ('busy', 'Band'), ('reserved', 'Bron'), ('disabled', 'O‘chiq')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='tables.tablecategory')),
            ],
            options={
                'verbose_name': 'Stol',
                'verbose_name_plural': 'Stollar',
                'ordering': ('number',),
            },
        ),
    ]
