from django.urls import path

from apps.ceo.views import (
    category_create_view,
    category_delete_view,
    category_list_view,
    category_update_view,
    cash_report_view,
    dashboard_view,
    employee_create_view,
    employee_delete_view,
    employee_list_view,
    employee_update_view,
    order_create_view,
    order_delete_view,
    order_detail_view,
    order_list_view,
    order_payment_view,
    order_update_view,
    panel_login_view,
    panel_logout_view,
    product_create_view,
    product_delete_view,
    product_image_delete_view,
    product_list_view,
    product_report_view,
    product_toggle_view,
    product_update_view,
    table_category_create_view,
    table_category_delete_view,
    table_category_list_view,
    table_category_update_view,
    table_create_view,
    table_delete_view,
    table_detail_view,
    table_list_view,
    table_qr_svg_view,
    table_update_view,
    public_table_qr_view,
)

urlpatterns = [
    path('', panel_login_view, name='panel-login'),
    path('login/', panel_login_view, name='panel-login'),
    path('logout/', panel_logout_view, name='panel-logout'),
    path('qr', public_table_qr_view, name='public-table-qr'),
    path('qr/', public_table_qr_view, name='public-table-qr-slash'),
    path('dashboard/', dashboard_view, name='ceo-dashboard'),
    path('dashboard/employees/', employee_list_view, name='employee-list'),
    path('dashboard/employees/create/', employee_create_view, name='employee-create'),
    path('dashboard/employees/<int:pk>/edit/', employee_update_view, name='employee-update'),
    path('dashboard/employees/<int:pk>/delete/', employee_delete_view, name='employee-delete'),
    path('dashboard/categories/', category_list_view, name='category-list'),
    path('dashboard/categories/create/', category_create_view, name='category-create'),
    path('dashboard/categories/<int:pk>/edit/', category_update_view, name='category-update'),
    path('dashboard/categories/<int:pk>/delete/', category_delete_view, name='category-delete'),
    path('dashboard/products/', product_list_view, name='product-list'),
    path('dashboard/products/create/', product_create_view, name='product-create'),
    path('dashboard/products/<int:pk>/edit/', product_update_view, name='product-update'),
    path('dashboard/products/<int:pk>/toggle/', product_toggle_view, name='product-toggle'),
    path('dashboard/products/<int:pk>/delete/', product_delete_view, name='product-delete'),
    path('dashboard/product-images/<int:pk>/delete/', product_image_delete_view, name='product-image-delete'),
    path('dashboard/tables/', table_list_view, name='table-list'),
    path('dashboard/tables/create/', table_create_view, name='table-create'),
    path('dashboard/tables/<int:pk>/', table_detail_view, name='table-detail'),
    path('dashboard/tables/<int:pk>/qr.svg', table_qr_svg_view, name='table-qr-svg'),
    path('dashboard/tables/<int:pk>/edit/', table_update_view, name='table-update'),
    path('dashboard/tables/<int:pk>/delete/', table_delete_view, name='table-delete'),
    path('dashboard/table-categories/', table_category_list_view, name='table-category-list'),
    path('dashboard/table-categories/create/', table_category_create_view, name='table-category-create'),
    path('dashboard/table-categories/<int:pk>/edit/', table_category_update_view, name='table-category-update'),
    path('dashboard/table-categories/<int:pk>/delete/', table_category_delete_view, name='table-category-delete'),
    path('dashboard/orders/', order_list_view, name='order-list'),
    path('dashboard/orders/create/', order_create_view, name='order-create'),
    path('dashboard/orders/<int:pk>/', order_detail_view, name='order-detail'),
    path('dashboard/orders/<int:pk>/payment/', order_payment_view, name='order-payment'),
    path('dashboard/orders/<int:pk>/edit/', order_update_view, name='order-update'),
    path('dashboard/orders/<int:pk>/delete/', order_delete_view, name='order-delete'),
    path('dashboard/reports/cash/', cash_report_view, name='cash-report'),
    path('dashboard/reports/products/', product_report_view, name='product-report'),
]
